name: Lint & PyTest on schedule
permissions:
  issues: read
  contents: write
  checks: write
  pull-requests: write

on: 
  schedule:
    - cron: '30 1 * * *'

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        branch:
          - main
          - dev
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      # Checkout codebase
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          token: ${{ github.token }}

      # Black formatter execution
      - name: Check files using the black formatter
        id: action_black
        uses: psf/black@stable
        with:
          options: "--pyi --safe --verbose"
          jupyter: true
          
      # Ruff linter execution
      - name: Check files using the Ruff linter
        uses: chartboost/ruff-action@v1
        with:
          args: "--fix --no-unsafe-fixes --no-cache"

      # Setup Python environtment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # Company dependancies installation
      - name: Clone JaxRK repository
        uses: actions/checkout@master
        with:
          name: exazyme/JaxRK
          path: resources/JaxRK/
          ref: main
          token: ${{ github.token }}
      - name: Clone protein_engineering_data repository
        uses: actions/checkout@master
        with:
          name: exazyme/protein_engineering_data
          path: resources/protein_engineering_data/
          ref: dev
          token: ${{ github.token }}
      - name: Clone enzyme_efficiency_prediction repository
        uses: actions/checkout@master
        with:
          name: exazyme/enzyme_efficiency_prediction
          path: resources/enzyme_efficiency_prediction/
          ref: dev
          token: ${{ github.token }}
      - name: Install Company dependancies
        run: |
          pip install --upgrade pip
          tree -L 2 resources
          cd resources/
          pip install -e "./JaxRK[ci]"
          pip install -e "./protein_engineering_data[ci, doc]"
          pip install -e "./enzyme_efficiency_prediction[ci, doc]"
          cd ../
          rm -rf resources
      
      - name: Configure dependancies
        run: |
          pip install .
          pip install pytest pytest-cov pytest-html
          pip install datasets==2.15.0
          pip list

      # PyTest and coverage
      - name: Run PyTest & Generate Coverage Report  
        run: |  
          coverage run -m pytest -v -s --junitxml=test-results.xml
          coverage report -m --fail-under=$MIN_COV

      # Comment test result on commmit
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: test-results.xml

      # Commit & push changes
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ github.token }}
          force: true